name: check
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Use Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 22.x
          cache: 'npm'
      - name: Use Deno
        uses: denoland/setup-deno@22d081ff2d3a40755e97629de92e3bcbfa7cf2ed # v2.0.5

      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Format
        run: npm run format:check
      - name: Type check
        run: npm run typecheck
      - name: Test
        run: npm test
      - name: Upload coverage
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Build
        run: npm run build
      - name: Test module resolution
        run: npm run test:modules
        working-directory: example
